server:
  port: 1050

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: consul
      port: 1049
      discovery:
        register: true
        instance-id: ${spring.application.name}-${random.value}
        health-check-path: /actuator/health
    gateway:
      discovery:
        locator:
          enabled: true
          register: true
          lower-case-service-id: true
      routes:
        - id: usuarios-service
          uri: lb://usuarios-service
          predicates:
            - Path=/api/usuarios/**
          filters:
            - RewritePath=/api/usuarios/(?<segment>.*), /api/usuarios/${segment}

        - id: articulos-service
          uri: lb://articulos-service
          predicates:
            - Path=/api/productos/**
          filters:
            - RewritePath=/api/productos/(?<segment>.*), /api/productos/${segment}

  spring:
    cloud:
      loadbalancer:
        cache:
          enabled: true
          caffeine:
            spec: maximumSize=1000,expireAfterWrite=10m

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
